-- 0023: transaction_kind 增加 'closing'（年结分录）。
--
-- 这一条**只加枚举值，不使用它**，因为 PostgreSQL 不允许在同一个事务里
-- 新增一个枚举值又引用它（"unsafe use of new value of enum type"）。
-- scripts/migrate.mjs 把每条迁移包在自己的事务里，所以真正用到 'closing'
-- 的约束与表放在 0024。
--
-- 为什么年结分录要有自己的 kind，而不是复用 'journal'：
--
-- 年结把各收入、费用科目的余额结转到留存收益。这笔分录按会计惯例记在
-- 财年最后一天。如果它和普通凭证长得一样，那么**那一年的损益表会变成
-- 全零**——因为损益表按期间聚合收入与费用科目，而年结分录恰好把它们
-- 全部冲平。用户第二年去看去年的损益表，会看到一张什么都没有的表。
--
-- 解决办法是让损益表能认出并排除它。可以靠一张标记表、一个布尔列，或者
-- 一个 kind。选 kind 是因为：
--   1. transactions.kind 本来就是「这笔账是哪一类事件」的答案，年结确实
--      是一类事件，不是普通凭证的一个属性；
--   2. 它自动带上既有的约束体系——0014 的 transactions_category_matches_kind
--      会要求它不带分类（年结没有分类可言），0024 把它并进那一支；
--   3. 交易列表、审计日志、导出全都已经在显示 kind，不用再各自学一个新字段。

alter type transaction_kind add value if not exists 'closing';
